version: '3.8'

services:
  fastapi:
    build: .
    ports:
      - "8000:8000"
    environment:
      - DATABASE_URL=postgresql://user:pass@db:5432/iris
      - MONGODB_URL=mongodb://mongo:27017/iris
    depends_on:
      - db
      - mongo

  db:
    image: postgres:15
    environment:
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: iris
    ports:
      - "5432:5432"

  mongo:
    image: mongo:6
    ports:
      - "27017:27017"